### ISSUE TITLE
Subir links de interés en la sección de Ocio y Aprendizaje

### ISSUE THREAD

**Issue by AraceliPintos** [PROGRAMA-INKUA-2023/ONE-TECH#35]
Usar como ejemplo el código que ya está hecho de "Links anses"

[Cambio lugar de cobro jubilaciones y pensiones](https://servicioscorp.anses.gob.ar/miansessitiov2/#/InvocaSistemas?IdMenu=10102)
[Solicitar la Pensión no Contributiva por Invalidez](https://servicioscorp.anses.gob.ar/miansessitiov2/#/InvocaSistemas?IdMenu=10901)
[Consultar recibo de haberes](https://servicioscorp.anses.gob.ar/clavelogon/logon.aspx?system=miansesv2)
[solicitar turno para Anses](https://servicioswww.anses.gob.ar/TurnosInternet/Burbujas/Pre []
![link ocio  y aprendizaje](https://github.com/PROGRAMA-INKUA-2023/ONE-TECH/assets/111717735/28579630-d694-45a1-bfd9-28e70459f815)

**Comment by CiroValentinMartinezG** [comment]
Hecho!
