### ISSUE TITLE
Subir la página a un servidor gratuito para poder acceder facilmente

### ISSUE THREAD

**Issue by AraceliPintos** [PROGRAMA-INKUA-2023/ONE-TECH#44]
usar esta herramienta:
https://app.netlify.com/login/email

loguearse con los datos de mail proporcionados onetech.g.1@gmail.com

**Comment by boujonmarcelo** [comment]
Se subió la página al siguiente servidor: Netlify
La dirección es: 
https://grantech-onetech.netlify.app/
